FROM 736626079/tensorflow:python3
RUN pip install --upgrade pip
RUN pip install opencv-python
RUN pip install lxml
RUN pip install pillow
RUN pip install matplotlib
RUN pip install keras
RUN pip install dicom